// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'User Guides',
      link: {
        type: 'generated-index',
        slug: '/guides',
        title: 'KreatorFlow User Guides',
        description: 'Learn how to use KreatorFlow to create amazing AI content.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides', // Auto-generates from docs/guides
        },
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      link: {
        type: 'generated-index',
        slug: '/faq',
        title: 'Frequently Asked Questions',
        description: 'Find answers to common questions about KreatorFlow.AI.'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq', // Auto-generates from docs/faq
        },
      ],
    },
  ]
}

export default sidebars
